---
title: "Day 1 note"
format:
  html:
    code-fold: true

---
## syllabus introduction
  - Tcp ip
  - how nodes are connected
  - ipv4 ipv6
  - tcp udp
  - ccna
  - ethernet
## Unit 1
## Day1
  - computer network
  - switch and routers
  - advantages application
    - file sharing
    - resource sharing
    - inexpensive setup
    - flexible handling
    - increase storage capacity
  - demerits
    - security concerns
    - virus and malware
    - lack of robustness
    - needs an efficient handler
  - business application
    - resource sharing
    - vpm
    - VOIP
    - desktop sharing
    - internet access
    - online news
    - digital library
    - security systems
    - gaming
    - m- commerse
    - GPS
    - sensor network
  - application fields
   - explain in exam
  - network models
    - PAN
    - LAN
    - CAN
    - MAN
    - WAN
  - Topological models
    - Bus
    - ring
    - star
    - extended star
    - heirarchical
    - mesh 
  - simplex
  - duplex 
    - half duplex
    - full duplex
## Day2
  - models
    - peer to peer modelsa
    - client server model 
      - flexibility
      - less cost
      - central control
      - improved netwoek
      - optimum resource utilization

    - active network models
      - can change network operation dynamically
  
## Unit 2
  - Protocols ,standards, interface and services
- standards:
  - De Facto 
    - By fact or by convention
    - Not approved by organizations but are adopted by them because of their wide use

  - De Jure
    - approved by official bodies
    - SMTP, UDP, TCP, IP
  - Reference models
    - OSI(https://networkdirection.net/articles/network-theory/osimodel/)
      - not used anymore
      - seven layers 
        - application   |          |
        - Presentation  |          |
         - Session      |          |
        - Transport     |          |
        - Network       | Physical |
        - Data Link     | Physical |
        - Physical      | Physical |
    - TCP,IP
  - Port numbers for popular sites 


